[package]
name = "wallclock-core"
version = "0.1.0"
edition = "2024"

[workspace.lints.clippy]
complexity = "warn"
perf = "warn"
style = "warn"
suspicious = "deny"

[dependencies]
aligned-vec = "0.6.4"
anyhow = "1.0.102"
base64 = "0.22.1"
chrono = "0.4.45"
compact_str = { version = "0.9.1", features = ["serde"] }
cosmic-text = "0.19.0"
drm = "0.15.0"
format = {
    git = "https://github.com/AkiraMiyakoda/rust-utils.git",
    branch = "main"
}
hmac-sha256 = "1.1.14"
image = {
    version = "0.25.10",
    default-features = false,
    features = ["jpeg", "webp"]
}
itertools = "0.14.0"
log = "0.4.32"
logger = {
    git = "https://github.com/AkiraMiyakoda/rust-utils.git",
    branch = "main"
}
mimalloc = "0.1.52"
mime = "0.3.17"
num-traits = "0.2.19"
reqwest = {
    version = "0.13.4",
    features = ["brotli", "deflate", "gzip", "json", "zstd"]
}
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
toml = "1.1.2"
uuid = { version = "1.23.3", features = ["v4"] }

[profile.dev.package."*"]
opt-level = 3

[profile.release]
strip = "symbols"
lto = "fat"
